# -*- coding: iso-8859-15 -*-
triggerList = []
triggerName = "GRun_V58_modifiable"

triggersDatasetMap = {
	'HLT_L1SingleMu16_v1': ['SingleMuon'],
	'HLT_HT350_DisplacedDijet80_Tight_DisplacedTrack_v2': ['DisplacedJet'],
	'HLT_Ele27_eta2p1_WPLoose_Gsf_LooseIsoPFTau20_v3': ['SingleElectron'],
	'HLT_Photon22_R9Id90_HE10_Iso40_EBOnly_PFMET40_v3': ['SinglePhoton'],
	'HLT_DoubleMediumIsoPFTau35_Trk1_eta2p1_Reg_v2': ['Tau'],
	'HLT_DoublePhoton85_v2': ['DoubleEG'],
	'HLT_Dimuon0er16_Jpsi_NoOS_NoVertexing_v2': ['Charmonium'],
	'HLT_PFHT650_WideJetMJJ900DEtaJJ1p5_v3': ['JetHT'],
	'HLT_DoubleMu23NoFiltersNoVtxDisplaced_v2': ['DoubleMuon'],
	'HLT_Photon30_v3': ['SinglePhoton'],
	'HLT_Mu17_TrkIsoVVL_TkMu8_TrkIsoVVL_v2': ['DoubleMuon'],
	'HLT_Mu55_v1': ['SingleMuon'],
	'MC_CaloMET_JetIdCleaned_v1': ['MonteCarlo'],
	'HLT_PFMETNoMu110_PFMHTNoMu110_IDTight_v1': ['MET'],
	'HLT_Rsq0p02_MR300_TriPFJet80_60_40_DoubleBTagCSV_p063_Mbb60_200_v1': ['BTagCSV'],
	'HLT_HT500_DisplacedDijet40_Inclusive_v2': ['DisplacedJet'],
	'HLT_Mu20_Mu10_v1': ['DoubleMuon'],
	'HLT_DoubleJetsC112_DoubleBTagCSV_p026_DoublePFJetsC172_v1': ['BTagCSV'],
	'HLT_Ele27_WPLoose_Gsf_CentralPFJet30_BTagCSV_p063_v1': ['SingleElectron'],
	'HLT_DiPFJet40_DEta3p5_MJJ600_PFMETNoMu80_v1': ['HTMHT'],
	'HLT_DiPFJet15_NoCaloMatched_v1': ['FSQJets'],
	'HLT_Mu17_v2': ['DoubleMuon'],
	'HLT_Mu33NoFiltersNoVtxDisplaced_DisplacedJet50_Loose_v2': ['SingleMuon'],
	'HLT_HT425_v1': ['DisplacedJet'],
	'MC_ReducedIterativeTracking_v1': ['MonteCarlo'],
	'HLT_Photon120_R9Id90_HE10_Iso40_EBOnly_VBF_v2': ['SinglePhoton'],
	'HLT_TkMu24_eta2p1_v2': ['SingleMuon'],
	'DST_HT250_CaloScouting_v2': ['ParkingScoutingMonitor', 'ScoutingCaloHT'],
	'HLT_PFJet400_v4': ['JetHT'],
	'HLT_Ele115_CaloIdVT_GsfTrkIdT_v2': ['SingleElectron'],
	'HLT_PFJet260_v4': ['JetHT'],
	'HLT_Photon36_R9Id90_HE10_IsoM_v3': ['SinglePhoton'],
	'HLT_AK4PFJet100_v3': ['HINPFJets'],
	'HLT_Photon50_R9Id90_HE10_Iso40_EBOnly_PFMET40_v3': ['SinglePhoton'],
	'HLT_PFMET300_v1': ['MET'],
	'HLT_Ele8_CaloIdL_TrackIdL_IsoVL_PFJet30_v1': ['DoubleEG'],
	'HLT_Ele27_eta2p1_WPLoose_Gsf_v2': ['SingleElectron'],
	'HLT_Photon50_R9Id90_HE10_IsoM_v3': ['SinglePhoton'],
	'HLT_Mu28NoFiltersNoVtx_DisplacedJet40_Loose_v2': ['SingleMuon'],
	'HLT_Mu28NoFiltersNoVtxDisplaced_Photon28_CaloIdL_v2': ['MuonEG'],
	'HLT_Mu7p5_Track3p5_Jpsi_v2': ['Charmonium'],
	'HLT_PFHT800_v2': ['JetHT'],
	'HLT_DiCentralPFJet55_PFMET110_v1': ['HTMHT'],
	'HLT_Ele27_eta2p1_WPTight_Gsf_v2': ['SingleElectron'],
	'HLT_AK4PFJet30_v3': ['HINPFJets'],
	'HLT_IsoMu22_v2': ['SingleMuon'],
	'HLT_Rsq0p30_v2': ['HTMHT'],
	'HLT_IsoTkMu27_v3': ['SingleMuon'],
	'HLT_Mu17_Photon35_CaloIdL_L1ISO_v3': ['MuonEG'],
	'HLT_DiPFJetAve80_HFJEC_v3': ['JetHT'],
	'HLT_PixelTracks_Multiplicity135ForEndOfFill_v1': ['HighMultiplicityEOF'],
	'HLT_RsqMR240_Rsq0p09_MR200_v2': ['HTMHT'],
	'MC_PFMET_v2': ['MonteCarlo'],
	'HLT_Mu40_eta2p1_PFJet200_PFJet50_v3': ['SingleMuon'],
	'HLT_LooseIsoPFTau50_Trk30_eta2p1_v3': ['Tau'],
	'HLT_PFMET120_BTagCSV_p067_v1': ['MET'],
	'HLT_PFHT650_4JetPt50_v1': ['JetHT'],
	'HLT_Ele10_CaloIdM_TrackIdM_CentralPFJet30_BTagCSV_p13_v1': ['DoubleEG'],
	'HLT_Photon75_R9Id90_HE10_Iso40_EBOnly_PFMET40_v3': ['SinglePhoton'],
	'HLT_PFHT350_DiPFJetAve90_PFAlphaT0p52_v2': ['HTMHT'],
	'HLT_TkMu20_v2': ['SingleMuon'],
	'HLT_IsoMu20_v3': ['SingleMuon'],
	'HLT_TrkMu17_DoubleTrkMu8NoFiltersNoVtx_v2': ['DoubleMuon'],
	'HLT_IsoMu18_CentralPFJet30_BTagCSV_p063_v1': ['SingleMuon'],
	'HLT_DoubleEle8_CaloIdM_TrackIdM_Mass8_PFHT250_v1': ['DoubleEG'],
	'MC_Diphoton10_10_R9Id_OR_IsoCaloId_AND_HE_R9Id_Mass10_v1': ['MonteCarlo'],
	'HLT_Photon90_CaloIdL_PFHT500_v3': ['SinglePhoton'],
	'HLT_LooseIsoPFTau50_Trk30_eta2p1_MET120_v1': ['Tau'],
	'HLT_Physics_v2': ['HLTPhysics'],
	'HLT_Mu42NoFiltersNoVtx_Photon42_CaloIdL_v2': ['MuonEG'],
	'HLT_AK4CaloJet30_v3': ['HINCaloJets'],
	'HLT_Photon22_R9Id90_HE10_Iso40_EBOnly_VBF_v2': ['SinglePhoton'],
	'HLT_Photon90_CaloIdL_PFHT600_v2': ['SinglePhoton'],
	'HLT_MET60_IsoTrk35_Loose_v1': ['MET'],
	'HLT_PFHT200_DiPFJetAve90_PFAlphaT0p63_v2': ['HTMHT'],
	'HLT_HT500to550_v1': ['ParkingHT500to550', 'ParkingScoutingMonitor'],
	'HLT_Rsq0p25_v2': ['HTMHT'],
	'HLT_DiPFJetAve60_v2': ['JetHT'],
	'HLT_Mu12_Photon25_CaloIdL_v3': ['MuonEG'],
	'HLT_Mu17_Photon22_CaloIdL_L1ISO_v1': ['MuonEG'],
	'HLT_DiPFJetAve140_v2': ['JetHT'],
	'HLT_Mu38NoFiltersNoVtxDisplaced_DisplacedJet60_Loose_v2': ['SingleMuon'],
	'HLT_IsoMu17_eta2p1_LooseIsoPFTau20_SingleL1_v4': ['SingleMuon'],
	'DST_CaloJet40_CaloScouting_PFScouting_v1': ['ParkingScoutingMonitor', 'ScoutingCaloCommissioning', 'ScoutingPFCommissioning'],
	'HLT_HT450to470_v1': ['ParkingHT450to470', 'ParkingScoutingMonitor'],
	'HLT_CaloJet500_NoJetID_v2': ['JetHT'],
	'HLT_DoubleJet90_Double30_TripleBTagCSV_p087_v1': ['BTagCSV'],
	'HLT_Dimuon10_Jpsi_Barrel_v2': ['Charmonium'],
	'HLT_DiPFJetAve35_HFJEC_v1': ['FSQJets'],
	'HLT_Mu17_TrkIsoVVL_Ele12_CaloIdL_TrackIdL_IsoVL_v3': ['MuonEG'],
	'HLT_Mu8_TrkIsoVVL_Ele17_CaloIdL_TrackIdL_IsoVL_v3': ['MuonEG'],
	'HLT_IsoMu17_eta2p1_MediumIsoPFTau40_Trk1_eta2p1_Reg_v5': ['SingleMuon'],
	'HLT_IsoMu17_eta2p1_MediumIsoPFTau35_Trk1_eta2p1_Reg_v3': ['SingleMuon'],
	'HLT_JetE70_NoBPTX3BX_NoHalo_v2': ['NoBPTX'],
	'HLT_CaloMHTNoPU90_PFMET90_PFMHT90_IDTight_BTagCSV_p067_v1': ['MET'],
	'HLT_VBF_DisplacedJet40_DisplacedTrack_2TrackIP2DSig5_v2': ['DisplacedJet'],
	'HLT_PFHT300_PFMET110_v1': ['HTMHT'],
	'HLT_RsqMR270_Rsq0p09_MR200_v2': ['HTMHT'],
	'HLT_DiPFJet15_FBEta3_NoCaloMatched_v1': ['FSQJets'],
	'HLT_Mu38NoFiltersNoVtx_DisplacedJet60_Loose_v2': ['SingleMuon'],
	'HLT_DiPFJet25_NoCaloMatched_v1': ['FSQJets'],
	'HLT_HT275_v1': ['DisplacedJet'],
	'HLT_Photon75_R9Id90_HE10_IsoM_v3': ['SinglePhoton'],
	'HLT_Photon120_R9Id90_HE10_IsoM_v3': ['SinglePhoton'],
	'HLT_Ele22_eta2p1_WPTight_Gsf_v3': ['SingleElectron'],
	'HLT_PFJet80_v4': ['JetHT'],
	'HLT_L1MinimumBiasHF_OR_v1': ['L1MinimumBias'],
	'HLT_Ele27_eta2p1_WPLoose_Gsf_DoubleMediumIsoPFTau35_Trk1_eta2p1_Reg_v2': ['SingleElectron'],
	'HLT_PFHT350_DiPFJetAve90_PFAlphaT0p53_v2': ['HTMHT'],
	'MC_DoubleEle5_CaloIdL_GsfTrkIdVL_MW_v2': ['MonteCarlo'],
	'HLT_HT2500_v1': ['JetHT'],
	'HLT_TrkMu15_DoubleTrkMu5NoFiltersNoVtx_v2': ['DoubleMuon'],
	'HLT_QuadPFJet_VBF_v4': ['JetHT'],
	'HLT_PFHT400_v2': ['JetHT'],
	'HLT_PFTau140_eta2p1_v1': ['Tau'],
	'HLT_Ele23_Ele12_CaloIdL_TrackIdL_IsoVL_DZ_v3': ['DoubleEG'],
	'HLT_DoubleJetsC100_DoubleBTagCSV_p014_DoublePFJetsC100MaxDeta1p6_v1': ['BTagCSV'],
	'HLT_Ele27_HighEta_Ele20_Mass55_v1': ['DoubleEG'],
	'HLT_DiPFJetAve100_HFJEC_v3': ['JetHT'],
	'AlCa_DoubleEle_CaloIdL_TrackIdL_IsoVL_DZ_v1': ['AlCaElectron'],
	'HLT_DoubleMu4_JpsiTrk_Displaced_v2': ['Charmonium'],
	'HLT_PFMET170_JetIdCleaned_v2': ['MET'],
	'HLT_HT350_DisplacedDijet80_DisplacedTrack_v2': ['DisplacedJet'],
	'MC_PFHT_v2': ['MonteCarlo'],
	'HLT_AK8DiPFJet280_200_TrimMass30_v1': ['JetHT'],
	'HLT_DoubleEle8_CaloIdM_TrackIdM_Mass8_PFHT300_v4': ['DoubleEG'],
	'HLT_PFHT450_SixJet40_v3': ['JetHT'],
	'HLT_DoubleEle24_22_eta2p1_WPLoose_Gsf_v2': ['DoubleEG'],
	'HLT_Mu17_TrkIsoVVL_TkMu8_TrkIsoVVL_DZ_v2': ['DoubleMuon'],
	'HLT_MonoCentralPFJet80_PFMETNoMu110_PFMHTNoMu110_IDTight_v1': ['MET'],
	'HLT_Mu17_TrkIsoVVL_Mu8_TrkIsoVVL_DZ_v2': ['DoubleMuon'],
	'HLT_PFHT350_v3': ['JetHT'],
	'HLT_Mu24_eta2p1_v2': ['SingleMuon'],
	'HLT_Ele23_CaloIdL_TrackIdL_IsoVL_v3': ['DoubleEG'],
	'HLT_DoubleJetsC100_DoubleBTagCSV_p026_DoublePFJetsC160_v1': ['BTagCSV'],
	'AlCa_LumiPixels_Random_v1': ['AlCaLumiPixels'],
	'MC_CaloHT_v1': ['MonteCarlo'],
	'HLT_Ele27_WPLoose_Gsf_v1': ['SingleElectron'],
	'HLT_RsqMR270_Rsq0p09_MR200_4jet_v2': ['HTMHT'],
	'HLT_AK8PFHT600_TrimR0p1PT0p03Mass50_BTagCSV_p20_v1': ['JetHT'],
	'HLT_Mu17_Photon30_CaloIdL_L1ISO_v3': ['MuonEG'],
	'HLT_DoubleEle33_CaloIdL_MW_v1': ['DoubleEG'],
	'DST_HT410_PFScouting_v1': ['ParkingScoutingMonitor', 'ScoutingPFHT'],
	'HLT_JetE50_NoBPTX3BX_NoHalo_v2': ['NoBPTX'],
	'HLT_Mu8_Ele8_CaloIdM_TrackIdM_Mass8_PFHT250_v1': ['MuonEG'],
	'HLT_QuadMuon0_Dimuon0_Jpsi_v2': ['Charmonium'],
	'HLT_Mu17_Mu8_SameSign_DZ_v1': ['DoubleMuon'],
	'HLT_PFMETNoMu120_PFMHTNoMu120_IDTight_v1': ['MET'],
	'HLT_Photon135_PFMET100_v1': ['SinglePhoton'],
	'HLT_VBF_DisplacedJet40_TightID_DisplacedTrack_v2': ['DisplacedJet'],
	'HLT_QuadPFJet_BTagCSV_p016_p11_VBF_Mqq240_v1': ['BTagCSV'],
	'HLT_Photon120_v3': ['SinglePhoton'],
	'HLT_Mu15_IsoVVVL_PFHT600_v3': ['SingleMuon'],
	'DST_L1HTT_CaloScouting_PFScouting_v1': ['ParkingScoutingMonitor', 'ScoutingCaloCommissioning', 'ScoutingPFCommissioning'],
	'HLT_DoubleMu38NoFiltersNoVtx_v2': ['DoubleMuon'],
	'HLT_Ele23_CaloIdM_TrackIdM_PFJet30_v3': ['DoubleEG'],
	'HLT_AK8DiPFJet280_200_TrimMass30_BTagCSV_p20_v1': ['JetHT'],
	'HLT_Mu23_TrkIsoVVL_Ele12_CaloIdL_TrackIdL_IsoVL_v3': ['MuonEG'],
	'HLT_PFTau120_eta2p1_v1': ['Tau'],
	'HLT_BTagMu_Jet300_Mu5_v2': ['BTagMu'],
	'HLT_QuadPFJet_BTagCSV_p016_p11_VBF_Mqq200_v1': ['BTagCSV'],
	'HLT_JetE30_NoBPTX_v2': ['NoBPTX'],
	'AlCa_DoubleEle_CaloIdL_TrackIdL_IsoVL_v1': ['AlCaElectron'],
	'HLT_Mu300_v1': ['SingleMuon'],
	'HLT_CaloMHTNoPU90_PFMET90_PFMHT90_IDTight_v2': ['MET'],
	'HLT_DoubleMu28NoFiltersNoVtxDisplaced_v2': ['DoubleMuon'],
	'HLT_HcalUTCA_v2': ['HcalNZS'],
	'AlCa_EcalPi0EEonly_v3': ['AlCaP0'],
	'HLT_DiPFJetAve320_v2': ['JetHT'],
	'HLT_Mu25_TkMu0_dEta18_Onia_v2': ['MuOnia'],
	'HLT_IsoMu22_CentralPFJet30_BTagCSV_p063_v1': ['SingleMuon'],
	'HLT_Ele27_eta2p1_WPLoose_Gsf_HT200_v2': ['SingleElectron'],
	'HLT_PFJet450_v4': ['JetHT'],
	'HLT_AK8PFHT700_TrimR0p1PT0p03Mass50_v3': ['JetHT'],
	'HLT_PixelTracks_Multiplicity85ForEndOfFill_v1': ['HighMultiplicity85EOF'],
	'HLT_Mu28NoFiltersNoVtx_CentralCaloJet40_v2': ['SingleMuon'],
	'HLT_IsoMu16_eta2p1_MET30_LooseIsoPFTau50_Trk30_eta2p1_v1': ['SingleMuon'],
	'HLT_L2Mu10_NoVertex_NoBPTX_v2': ['NoBPTX'],
	'MC_CaloMET_v1': ['MonteCarlo'],
	'MC_DoubleMu_TrkIsoVVL_DZ_v1': ['MonteCarlo'],
	'HLT_IsoMu18_TriCentralPFJet50_40_30_v2': ['SingleMuon'],
	'HLT_PixelTracks_Multiplicity110ForEndOfFill_v1': ['HighMultiplicityEOF'],
	'HLT_PFJet320_v4': ['JetHT'],
	'HLT_Mu38NoFiltersNoVtxDisplaced_DisplacedJet60_Tight_v2': ['SingleMuon'],
	'HLT_DoubleMu4_LowMassNonResonantTrk_Displaced_v2': ['DoubleMuonLowMass'],
	'HLT_Mu16_TkMu0_dEta18_Onia_v2': ['MuOnia'],
	'HLT_Ele22_eta2p1_WPLoose_Gsf_LooseIsoPFTau20_SingleL1_v2': ['SingleElectron'],
	'HLT_DiPFJetAve200_v2': ['JetHT'],
	'HLT_PFHT300_PFMET100_v1': ['HTMHT'],
	'HLT_IsoMu16_eta2p1_MET30_v1': ['SingleMuon'],
	'HLT_IsoMu27_v3': ['SingleMuon'],
	'HLT_BTagMu_DiJet40_Mu5_v2': ['BTagMu'],
	'HLT_PFHT250_v2': ['JetHT'],
	'HLT_Dimuon8_PsiPrime_Barrel_v2': ['Charmonium'],
	'HLT_Mu7p5_Track7_Jpsi_v2': ['Charmonium'],
	'HLT_DiPFJet25_FBEta3_NoCaloMatched_v1': ['FSQJets'],
	'HLT_Photon500_v1': ['SinglePhoton'],
	'HLT_PFMETNoMu90_PFMHTNoMu90_IDTight_v1': ['MET'],
	'HLT_Diphoton30PV_18PV_R9Id_AND_IsoCaloId_AND_HE_R9Id_DoublePixelVeto_Mass55_v1': ['DoubleEG'],
	'HLT_PFHT600_v3': ['JetHT'],
	'HLT_PFHT550_4JetPt50_v1': ['JetHT'],
	'HLT_Ele45_CaloIdVT_GsfTrkIdT_PFJet200_PFJet50_v3': ['SingleElectron'],
	'HLT_Ele23_WPLoose_Gsf_CentralPFJet30_BTagCSV_p063_v1': ['SingleElectron'],
	'HLT_Mu16_TkMu0_dEta18_Phi_v2': ['MuOnia'],
	'HLT_VBF_DisplacedJet40_Hadronic_2PromptTrack_v2': ['DisplacedJet'],
	'AlCa_RPCMuonNoTriggers_v2': ['RPCMonitor'],
	'HLT_Mu17_TkMu8_DZ_v2': ['DoubleMuon'],
	'HLT_AK4PFJet50_v3': ['HINPFJets'],
	'HLT_DiPFJetAve80_v2': ['JetHT'],
	'MC_IsoTkMu15_v3': ['MonteCarlo'],
	'HLT_Ele23_Ele12_CaloIdL_TrackIdL_IsoVL_v3': ['DoubleEG'],
	'HLT_Photon50_v3': ['SinglePhoton'],
	'HLT_Ele17_Ele12_CaloIdL_TrackIdL_IsoVL_DZ_v3': ['DoubleEG'],
	'HLT_Ele30WP60_Ele8_Mass55_v2': ['DoubleEG'],
	'HLT_Photon175_v3': ['SinglePhoton'],
	'HLT_PFMET90_PFMHT90_IDTight_v2': ['MET'],
	'HLT_Mu30_Ele30_CaloIdL_GsfTrkIdVL_v3': ['MuonEG'],
	'HLT_Ele12_CaloIdL_TrackIdL_IsoVL_v3': ['DoubleEG'],
	'HLT_PFJet15_NoCaloMatched_v3': ['FSQJets'],
	'MC_Ele15_Ele10_CaloIdL_TrackIdL_IsoVL_DZ_v2': ['MonteCarlo'],
	'HLT_Dimuon13_PsiPrime_v2': ['Charmonium'],
	'AlCa_LumiPixels_ZeroBias_v2': ['AlCaLumiPixels'],
	'HLT_Mu14er_PFMET100_v1': ['MET'],
	'HLT_DoubleEle33_CaloIdL_GsfTrkIdVL_v3': ['DoubleEG'],
	'HLT_HISinglePhoton60_v2': ['HINPhoton'],
	'HLT_Mu10_TrkIsoVVL_DiPFJet40_DEta3p5_MJJ750_HTT350_PFMETNoMu60_v1': ['SingleMuon'],
	'HLT_Mu16_eta2p1_MET30_v1': ['SingleMuon'],
	'AlCa_EcalPhiSym_v3': ['AlCaPhiSym'],
	'HLT_VBF_DisplacedJet40_VTightID_Hadronic_v2': ['DisplacedJet'],
	'HLT_IsoMu17_eta2p1_v3': ['SingleMuon'],
	'HLT_Rsq0p02_MR300_TriPFJet80_60_40_BTagCSV_p063_p20_Mbb60_200_v1': ['BTagCSV'],
	'HLT_PFHT200_PFAlphaT0p51_v2': ['HTMHT'],
	'HLT_Ele30WP60_SC4_Mass55_v3': ['DoubleEG'],
	'HLT_Mu6_PFHT200_PFMET100_v1': ['MET'],
	'HLT_Mu15_IsoVVVL_PFHT350_PFMET50_v2': ['SingleMuon'],
	'HLT_Photon120_R9Id90_HE10_Iso40_EBOnly_PFMET40_v3': ['SinglePhoton'],
	'HLT_Ele15_IsoVVVL_PFHT350_v2': ['SingleElectron'],
	'HLT_DiPFJetAve260_v2': ['JetHT'],
	'HLT_PFJet60_v4': ['JetHT'],
	'MC_Ele5_WPLoose_Gsf_v2': ['MonteCarlo'],
	'HLT_Photon165_R9Id90_HE10_IsoM_v3': ['SinglePhoton'],
	'HLT_L1_TripleJet_VBF_v4': ['JetHT'],
	'HLT_PFJet500_v4': ['JetHT'],
	'HLT_Photon75_R9Id90_HE10_Iso40_EBOnly_VBF_v2': ['SinglePhoton'],
	'HLT_Photon90_R9Id90_HE10_Iso40_EBOnly_PFMET40_v3': ['SinglePhoton'],
	'HLT_Dimuon6_Jpsi_NoVertexing_v2': ['Charmonium'],
	'HLT_Photon90_R9Id90_HE10_IsoM_v3': ['SinglePhoton'],
	'HLT_PFHT250_DiPFJetAve90_PFAlphaT0p55_v2': ['HTMHT'],
	'HLT_Ele105_CaloIdVT_GsfTrkIdT_v3': ['SingleElectron'],
	'DST_HT450_PFScouting_v1': ['ParkingScoutingMonitor', 'ScoutingPFHT'],
	'HLT_HT550to650_v1': ['ParkingHT550to650', 'ParkingScoutingMonitor'],
	'HLT_QuadPFJet_BTagCSV_p016_VBF_Mqq460_v1': ['BTagCSV'],
	'HLT_Diphoton30_18_Solid_R9Id_AND_IsoCaloId_AND_HE_R9Id_Mass55_v1': ['DoubleEG'],
	'HLT_HT430to450_v1': ['ParkingHT430to450', 'ParkingScoutingMonitor'],
	'MC_AK8PFHT_v2': ['MonteCarlo'],
	'HLT_QuadJet45_TripleBTagCSV_p087_v1': ['BTagCSV'],
	'HLT_HT350_DisplacedDijet40_Inclusive_v1': ['DisplacedJet'],
	'MC_AK8PFJets_v2': ['MonteCarlo'],
	'HLT_DoubleMu4_3_Jpsi_Displaced_v2': ['Charmonium'],
	'HLT_DoubleMediumIsoPFTau40_Trk1_eta2p1_Reg_v4': ['Tau'],
	'HLT_Ele8_CaloIdM_TrackIdM_PFJet30_v3': ['DoubleEG'],
	'HLT_IsoTkMu20_v4': ['SingleMuon'],
	'HLT_Mu33NoFiltersNoVtxDisplaced_DisplacedJet50_Tight_v2': ['SingleMuon'],
	'HLT_DoublePhoton60_v1': ['DoubleEG'],
	'HLT_AK4PFJet80_v3': ['HINPFJets'],
	'HLT_Dimuon0_Upsilon_Muon_v2': ['MuOnia'],
	'HLT_HT470to500_v1': ['ParkingHT470to500', 'ParkingScoutingMonitor'],
	'HLT_Mu23_TrkIsoVVL_Ele8_CaloIdL_TrackIdL_IsoVL_v1': ['MuonEG'],
	'HLT_DoubleJetsC100_SingleBTagCSV_p014_v1': ['BTagCSV'],
	'AlCa_EcalEtaEEonly_v3': ['AlCaP0'],
	'HLT_Ele15_IsoVVVL_BTagCSV_p067_PFHT400_v1': ['SingleElectron'],
	'HLT_Ele23_WPLoose_Gsf_TriCentralPFJet50_40_30_v2': ['SingleElectron'],
	'HLT_Mu12_Photon25_CaloIdL_L1ISO_v3': ['MuonEG'],
	'HLT_Ele35_CaloIdVT_GsfTrkIdT_PFJet150_PFJet50_v1': ['SingleElectron'],
	'HLT_HT350_DisplacedDijet40_DisplacedTrack_v2': ['DisplacedJet'],
	'HLT_DoubleJetsC100_SingleBTagCSV_p014_SinglePFJetC350_v1': ['BTagCSV'],
	'HLT_AK4CaloJet100_v2': ['HINCaloJets'],
	'HLT_HISinglePhoton10_v2': ['HINPhoton'],
	'HLT_Ele23_CaloIdL_TrackIdL_IsoVL_PFJet30_v3': ['DoubleEG'],
	'HLT_BTagMu_DiJet20_Mu5_v2': ['BTagMu'],
	'HLT_AK8PFJet360_TrimMass30_v3': ['JetHT'],
	'HLT_HT650_v2': ['ParkingHT650', 'ParkingScoutingMonitor'],
	'HLT_HT750_DisplacedDijet80_Inclusive_v2': ['DisplacedJet'],
	'HLT_MET200_v1': ['MET'],
	'HLT_L2Mu10_NoVertex_NoBPTX3BX_NoHalo_v2': ['NoBPTX'],
	'HLT_DiPFJetAve300_HFJEC_v3': ['JetHT'],
	'HLT_MonoCentralPFJet80_PFMETNoMu90_PFMHTNoMu90_IDTight_v1': ['MET'],
	'HLT_Ele15_IsoVVVL_PFHT600_v3': ['SingleElectron'],
	'HLT_PFMET400_v1': ['MET'],
	'HLT_Mu7p5_Track2_Jpsi_v2': ['Charmonium'],
	'HLT_Dimuon0er16_Jpsi_NoVertexing_v2': ['Charmonium'],
	'HLT_ZeroBias_IsolatedBunches_v1': ['ZeroBias'],
	'HLT_HT400_DisplacedDijet40_Inclusive_v2': ['DisplacedJet'],
	'HLT_Mu8_v3': ['DoubleMuon'],
	'HLT_IsoTrackHB_v1': ['Commissioning'],
	'HLT_PFMET170_HBHECleaned_v2': ['MET'],
	'MC_PFMHT_v2': ['MonteCarlo'],
	'HLT_JetE30_NoBPTX3BX_NoHalo_v2': ['NoBPTX'],
	'HLT_PFMET100_PFMHT100_IDTight_v2': ['MET'],
	'DST_ZeroBias_PFScouting_v1': ['ParkingScoutingMonitor', 'ScoutingPFCommissioning'],
	'HLT_Mu6_PFHT200_PFMET80_BTagCSV_p067_v1': ['MET'],
	'HLT_Ele27_WPLoose_Gsf_WHbbBoost_v2': ['SingleElectron'],
	'HLT_Mu40_TkMu11_v2': ['DoubleMuon'],
	'HLT_DiPFJet40_DEta3p5_MJJ600_PFMETNoMu140_v1': ['HTMHT'],
	'HLT_BTagMu_DiJet70_Mu5_v2': ['BTagMu'],
	'HLT_Mu20_v2': ['SingleMuon'],
	'HLT_Mu8_TrkIsoVVL_Ele23_CaloIdL_TrackIdL_IsoVL_v3': ['MuonEG'],
	'HLT_Photon75_v3': ['SinglePhoton'],
	'MC_AK4PFJets_v2': ['MonteCarlo'],
	'HLT_PFMETNoMu100_PFMHTNoMu100_IDTight_v1': ['MET'],
	'HLT_HT200_DisplacedDijet40_DisplacedTrack_v1': ['DisplacedJet'],
	'HLT_L2Mu40_NoVertex_3Sta_NoBPTX3BX_NoHalo_v2': ['NoBPTX'],
	'HLT_Diphoton30_18_R9Id_OR_IsoCaloId_AND_HE_R9Id_Mass90_v1': ['DoubleEG'],
	'HLT_Mu7p5_Track7_Upsilon_v2': ['MuOnia'],
	'HLT_PFHT250_DiPFJetAve90_PFAlphaT0p58_v2': ['HTMHT'],
	'HLT_L1SingleMuOpen_v2': ['SingleMuon'],
	'HLT_Ele27_WPLoose_Gsf_TriCentralPFJet50_40_30_v1': ['SingleElectron'],
	'HLT_IsoTkMu22_v2': ['SingleMuon'],
	'HLT_DiSC30_18_EIso_AND_HE_Mass70_v1': ['Commissioning'],
	'HLT_Mu8_Ele8_CaloIdM_TrackIdM_Mass8_PFHT300_v4': ['MuonEG'],
	'HLT_DiMu9_Ele9_CaloIdL_TrackIdL_v3': ['MuonEG'],
	'HLT_DiPFJetAve160_HFJEC_v3': ['JetHT'],
	'HLT_PFJet25_NoCaloMatched_v1': ['FSQJets'],
	'HLT_IsoMu20_eta2p1_LooseIsoPFTau20_v3': ['SingleMuon'],
	'HLT_Ele23_WPLoose_Gsf_v3': ['SingleElectron'],
	'HLT_Mu17_TrkIsoVVL_Mu8_TrkIsoVVL_v2': ['DoubleMuon'],
	'HLT_Random_v1': ['ZeroBias'],
	'HLT_HT200_v1': ['DisplacedJet'],
	'HLT_PFJet140_v4': ['JetHT'],
	'HLT_PFHT400_SixJet30_DoubleBTagCSV_p056_v1': ['JetHT'],
	'HLT_LooseIsoPFTau50_Trk30_eta2p1_MET80_v1': ['Tau'],
	'HLT_Dimuon8_Upsilon_Barrel_v2': ['MuOnia'],
	'HLT_Mu27_TkMu8_v2': ['DoubleMuon'],
	'HLT_L1Tech_DT_GlobalOR_v2': ['Commissioning'],
	'HLT_DiPFJetAve220_HFJEC_v3': ['JetHT'],
	'HLT_DoubleMu4_3_Bs_v2': ['Charmonium'],
	'HLT_PFMET120_Mu5_v1': ['MET'],
	'HLT_MonoCentralPFJet80_PFMETNoMu100_PFMHTNoMu100_IDTight_v1': ['MET'],
	'HLT_DiPFJetAve60_HFJEC_v3': ['JetHT'],
	'HLT_QuadMuon0_Dimuon0_Upsilon_v2': ['MuOnia'],
	'HLT_L2Mu10_v1': ['SingleMuon'],
	'HLT_Mu50_v2': ['SingleMuon'],
	'HLT_Photon50_R9Id90_HE10_Iso40_EBOnly_VBF_v2': ['SinglePhoton'],
	'HLT_VBF_DisplacedJet40_DisplacedTrack_v2': ['DisplacedJet'],
	'HLT_Mu3er_PFHT140_PFMET125_v1': ['MET'],
	'AlCa_EcalPi0EBonly_v3': ['AlCaP0'],
	'HLT_MET90_IsoTrk50_v2': ['MET'],
	'HLT_HISinglePhoton20_v2': ['HINPhoton'],
	'HLT_ECALHT800_v2': ['DoubleEG'],
	'HLT_PFMET110_PFMHT110_IDTight_v2': ['MET'],
	'HLT_BTagMu_DiJet110_Mu5_v2': ['BTagMu'],
	'DST_DoubleMu3_Mass10_PFScouting_v1': ['ParkingScoutingMonitor', 'ScoutingPFMuons'],
	'HLT_PFHT900_v1': ['JetHT'],
	'HLT_DoubleMu33NoFiltersNoVtx_v2': ['DoubleMuon'],
	'HLT_PFTau95_eta2p1_v1': ['Tau'],
	'HLT_Mu45_eta2p1_v2': ['SingleMuon'],
	'HLT_Ele23_WPLoose_Gsf_WHbbBoost_v2': ['SingleElectron'],
	'HLT_Ele17_CaloIdL_TrackIdL_IsoVL_PFJet30_v1': ['DoubleEG'],
	'HLT_Ele12_CaloIdL_TrackIdL_IsoVL_PFJet30_v3': ['DoubleEG'],
	'HLT_DoubleJetsC100_SingleBTagCSV_p026_SinglePFJetC350_v1': ['BTagCSV'],
	'HLT_Ele17_CaloIdM_TrackIdM_PFJet30_v1': ['DoubleEG'],
	'HLT_MonoCentralPFJet80_PFMETNoMu120_PFMHTNoMu120_IDTight_v1': ['MET'],
	'HLT_Ele22_eta2p1_WPLoose_Gsf_v3': ['SingleElectron'],
	'HLT_VBF_DisplacedJet40_Hadronic_v2': ['DisplacedJet'],
	'HLT_Mu30_eta2p1_PFJet150_PFJet50_v1': ['SingleMuon'],
	'HLT_L2Mu35_NoVertex_3Sta_NoBPTX3BX_NoHalo_v2': ['NoBPTX'],
	'HLT_PFHT650_v3': ['JetHT'],
	'HLT_DoubleMu8_Mass8_PFHT250_v1': ['DoubleMuon'],
	'HLT_HT250_DisplacedDijet40_DisplacedTrack_v2': ['DisplacedJet'],
	'HLT_Photon36_R9Id90_HE10_Iso40_EBOnly_VBF_v2': ['SinglePhoton'],
	'HLT_Mu17_Mu8_DZ_v2': ['DoubleMuon'],
	'MC_DoubleMuNoFiltersNoVtx_v1': ['MonteCarlo'],
	'HLT_L2DoubleMu38_NoVertex_2Cha_Angle2p5_Mass10_v2': ['DoubleMuon'],
	'HLT_TkMu27_v2': ['SingleMuon'],
	'HLT_Mu33NoFiltersNoVtxDisplaced_Photon33_CaloIdL_v2': ['MuonEG'],
	'HLT_PFHT300_DiPFJetAve90_PFAlphaT0p53_v2': ['HTMHT'],
	'HLT_Photon90_v3': ['SinglePhoton'],
	'HLT_PFMET120_PFMHT120_IDTight_v2': ['MET'],
	'HLT_Photon36_R9Id90_HE10_Iso40_EBOnly_PFMET40_v3': ['SinglePhoton'],
	'HLT_QuadJet45_DoubleBTagCSV_p087_v1': ['BTagCSV'],
	'HLT_HcalPhiSym_v2': ['HcalNZS'],
	'HLT_PFMET170_NoiseCleaned_v3': ['MET'],
	'HLT_MET75_IsoTrk50_v2': ['MET'],
	'HLT_Ele12_CaloIdM_TrackIdM_PFJet30_v3': ['DoubleEG'],
	'DST_L1DoubleMu_PFScouting_v1': ['ParkingScoutingMonitor', 'ScoutingPFCommissioning'],
	'HLT_MET250_v1': ['MET'],
	'MC_DoubleGlbTrkMu_TrkIsoVVL_DZ_v1': ['MonteCarlo'],
	'HLT_Mu38NoFiltersNoVtx_Photon38_CaloIdL_v2': ['MuonEG'],
	'HLT_VBF_DisplacedJet40_TightID_Hadronic_v2': ['DisplacedJet'],
	'HLT_Mu7p5_L2Mu2_Upsilon_v2': ['MuOnia'],
	'HLT_Ele17_CaloIdL_TrackIdL_IsoVL_v2': ['DoubleEG'],
	'HLT_PFHT650_WideJetMJJ950DEtaJJ1p5_v3': ['JetHT'],
	'HLT_L1SingleMuOpen_DT_v2': ['Commissioning'],
	'HLT_DiPFJetAve25_HFJEC_v1': ['FSQJets'],
	'HLT_Mu20_Mu10_DZ_v1': ['DoubleMuon'],
	'HLT_DiPFJetAve500_v2': ['JetHT'],
	'HLT_PFMET170_NotCleaned_v1': ['MET'],
	'HLT_Mu20_Mu10_SameSign_DZ_v1': ['DoubleMuon'],
	'HLT_Photon42_R9Id85_OR_CaloId24b40e_Iso50T80L_Photon25_AND_HE10_R9Id65_Eta2_Mass15_v2': ['DoubleEG'],
	'HLT_Mu15_IsoVVVL_BTagCSV_p067_PFHT400_v1': ['SingleMuon'],
	'MC_AK4CaloJets_v1': ['MonteCarlo'],
	'HLT_Dimuon0_Phi_Barrel_v2': ['MuOnia'],
	'HLT_PFHT450_SixJet40_BTagCSV_p056_v1': ['JetHT'],
	'HLT_PFHT475_v2': ['JetHT'],
	'HLT_Mu7p5_Track2_Upsilon_v2': ['MuOnia'],
	'HLT_Mu12_Photon25_CaloIdL_L1OR_v3': ['MuonEG'],
	'HLT_Dimuon20_Jpsi_v2': ['Charmonium'],
	'HLT_PFHT400_DiPFJetAve90_PFAlphaT0p52_v2': ['HTMHT'],
	'HLT_Photon165_HE10_v3': ['SinglePhoton'],
	'HLT_Dimuon0_Jpsi_Muon_v2': ['Charmonium'],
	'HLT_Dimuon13_Upsilon_v2': ['MuOnia'],
	'HLT_IsoMu22_TriCentralPFJet50_40_30_v2': ['SingleMuon'],
	'HLT_AK4CaloJet40_v2': ['HINCaloJets'],
	'HLT_Diphoton30_18_R9Id_OR_IsoCaloId_AND_HE_R9Id_DoublePixelSeedMatch_Mass70_v1': ['DoubleEG'],
	'MC_IsoMu_v4': ['MonteCarlo'],
	'HLT_DoubleJet90_Double30_DoubleBTagCSV_p087_v1': ['BTagCSV'],
	'HLT_PFJet40_v4': ['JetHT'],
	'HLT_DoubleEle33_CaloIdL_v1': ['DoubleEG'],
	'HLT_AK8DiPFJet250_200_TrimMass30_BTagCSV_p20_v1': ['JetHT'],
	'HLT_DiPFJetAve40_v2': ['JetHT'],
	'HLT_PFHT200_DiPFJetAve90_PFAlphaT0p57_v2': ['HTMHT'],
	'HLT_QuadPFJet_BTagCSV_p016_VBF_Mqq500_v1': ['BTagCSV'],
	'HLT_DoubleIsoMu17_eta2p1_v3': ['SingleMuon'],
	'HLT_DoubleJetsC100_SingleBTagCSV_p026_v1': ['BTagCSV'],
	'HLT_AK4CaloJet80_v2': ['HINCaloJets'],
	'HLT_L2DoubleMu23_NoVertex_v2': ['DoubleMuon'],
	'HLT_DoubleJetsC112_DoubleBTagCSV_p014_DoublePFJetsC112MaxDeta1p6_v1': ['BTagCSV'],
	'HLT_HT550_DisplacedDijet40_Inclusive_v2': ['DisplacedJet'],
	'DST_L1HTT_BTagScouting_v1': ['ParkingScoutingMonitor', 'ScoutingPFCommissioning'],
	'HLT_Photon36_v3': ['SinglePhoton'],
	'AlCa_RPCMuonNormalisation_v2': ['RPCMonitor'],
	'HLT_HISinglePhoton40_v2': ['HINPhoton'],
	'HLT_PFHT400_DiPFJetAve90_PFAlphaT0p51_v2': ['HTMHT'],
	'DST_HT450_BTagScouting_v1': ['ParkingScoutingMonitor', 'ScoutingPFHT'],
	'HLT_Mu8_DiEle12_CaloIdL_TrackIdL_v3': ['MuonEG'],
	'DST_CaloJet40_BTagScouting_v1': ['ParkingScoutingMonitor', 'ScoutingPFCommissioning'],
	'HLT_AK8PFHT650_TrimR0p1PT0p03Mass50_v2': ['JetHT'],
	'HLT_Photon30_R9Id90_HE10_IsoM_v3': ['SinglePhoton'],
	'HLT_GlobalRunHPDNoise_v3': ['HcalHPDNoise'],
	'HLT_TripleMu_12_10_5_v2': ['DoubleMuon'],
	'MC_AK8TrimPFJets_v2': ['MonteCarlo'],
	'HLT_PFJet200_v4': ['JetHT'],
	'HLT_PFHT125_v1': ['JetHT'],
	'HLT_MET300_v1': ['MET'],
	'HLT_Mu8_TrkIsoVVL_v3': ['DoubleMuon'],
	'HLT_Photon36_R9Id85_OR_CaloId24b40e_Iso50T80L_Photon22_AND_HE10_R9Id65_Eta2_Mass15_v2': ['DoubleEG'],
	'DST_L1DoubleMu_BTagScouting_v1': ['ParkingScoutingMonitor', 'ScoutingPFCommissioning'],
	'HLT_AK4CaloJet50_v2': ['HINCaloJets'],
	'HLT_PixelTracks_Multiplicity60ForEndOfFill_v1': ['HighMultiplicityEOF'],
	'HLT_ZeroBias_v2': ['ZeroBias'],
	'HLT_PFHT750_4JetPt50_v3': ['JetHT'],
	'HLT_Mu10_CentralPFJet30_BTagCSV_p13_v1': ['DoubleMuon'],
	'HLT_Ele16_Ele12_Ele8_CaloIdL_TrackIdL_v3': ['DoubleEG'],
	'HLT_HISinglePhoton15_v2': ['HINPhoton'],
	'HLT_HT2000_v1': ['JetHT'],
	'DST_ZeroBias_BTagScouting_v1': ['ParkingScoutingMonitor', 'ScoutingPFCommissioning'],
	'HLT_Ele22_eta2p1_WPLoose_Gsf_LooseIsoPFTau20_v3': ['SingleElectron'],
	'HLT_IsoTrackHE_v1': ['Commissioning'],
	'MC_CaloMHT_v1': ['MonteCarlo'],
	'HLT_Ele32_eta2p1_WPTight_Gsf_v2': ['SingleElectron'],
	'HLT_HcalNZS_v2': ['HcalNZS'],
	'HLT_DoubleMu4_PsiPrimeTrk_Displaced_v2': ['Charmonium'],
	'HLT_Ele15_IsoVVVL_PFHT350_PFMET50_v2': ['SingleElectron'],
	'HLT_Ele17_Ele12_CaloIdL_TrackIdL_IsoVL_v3': ['DoubleEG'],
	'HLT_PFHT400_SixJet30_v3': ['JetHT'],
	'HLT_Mu350_v1': ['SingleMuon'],
	'AlCa_EcalEtaEBonly_v3': ['AlCaP0'],
	'HLT_DoubleEle33_CaloIdL_GsfTrkIdVL_MW_v3': ['DoubleEG'],
	'HLT_Photon300_NoHE_v2': ['SinglePhoton'],
	'DST_DoubleMu3_Mass10_BTagScouting_v1': ['ParkingScoutingMonitor', 'ScoutingPFMuons'],
	'HLT_Photon22_R9Id90_HE10_IsoM_v2': ['SinglePhoton'],
	'HLT_Mu27_v2': ['SingleMuon'],
	'HLT_IsoTkMu18_v2': ['SingleMuon'],
	'AlCa_SingleEle_WPVeryLoose_Gsf_v1': ['AlCaElectron'],
	'HLT_HT650_DisplacedDijet80_Inclusive_v2': ['DisplacedJet'],
	'HLT_Photon22_v2': ['SinglePhoton'],
	'HLT_Ele27_eta2p1_WPLoose_Gsf_DoubleMediumIsoPFTau40_Trk1_eta2p1_Reg_v3': ['SingleElectron'],
	'HLT_L2DoubleMu28_NoVertex_2Cha_Angle2p5_Mass10_v2': ['DoubleMuon'],
	'DST_HT410_BTagScouting_v1': ['ParkingScoutingMonitor', 'ScoutingPFHT'],
	'HLT_L1MinimumBiasHF_AND_v1': ['L1MinimumBias'],
	'HLT_HT575_v1': ['DisplacedJet'],
	'HLT_Mu30_TkMu11_v2': ['DoubleMuon'],
	'HLT_PFHT300_DiPFJetAve90_PFAlphaT0p54_v2': ['HTMHT'],
	'HLT_DiPFJetAve400_v2': ['JetHT'],
	'HLT_DiPFJetAve15_HFJEC_v1': ['FSQJets'],
	'MC_AK8CaloHT_v1': ['MonteCarlo'],
	'HLT_AK8DiPFJet250_200_TrimMass30_v1': ['JetHT'],
	'HLT_Diphoton30EB_18EB_R9Id_OR_IsoCaloId_AND_HE_R9Id_DoublePixelVeto_Mass55_v1': ['DoubleEG'],
	'HLT_RsqMR240_Rsq0p09_MR200_4jet_v2': ['HTMHT'],
	'AlCa_RPCMuonNoHits_v2': ['RPCMonitor'],
	'HLT_Photon90_R9Id90_HE10_Iso40_EBOnly_VBF_v2': ['SinglePhoton'],
	'HLT_PixelTracks_Multiplicity160ForEndOfFill_v1': ['HighMultiplicityEOF'],
	'HLT_HT325_v1': ['DisplacedJet'],
	'HLT_Photon600_v1': ['SinglePhoton'],
	'HLT_Mu15_IsoVVVL_PFHT350_v2': ['SingleMuon'],
	'HLT_VBF_DisplacedJet40_VTightID_DisplacedTrack_v2': ['DisplacedJet'],
	'HLT_VBF_DisplacedJet40_VVTightID_Hadronic_v2': ['DisplacedJet'],
	'HLT_Mu17_TrkIsoVVL_v2': ['DoubleMuon'],
	'HLT_Photon26_R9Id85_OR_CaloId24b40e_Iso50T80L_Photon16_AND_HE10_R9Id65_Eta2_Mass60_v2': ['DoubleEG'],
	'HLT_Dimuon16_Jpsi_v2': ['Charmonium'],
	'HLT_IsoMu17_eta2p1_LooseIsoPFTau20_v4': ['SingleMuon'],
	'HLT_DoubleMu18NoFiltersNoVtx_v2': ['DoubleMuon'],
	'HLT_VBF_DisplacedJet40_VVTightID_DisplacedTrack_v2': ['DisplacedJet'],
	'HLT_HT410to430_v1': ['ParkingHT410to430', 'ParkingScoutingMonitor'],
	'HLT_Photon250_NoHE_v2': ['SinglePhoton'],
	'HLT_IsoMu18_v2': ['SingleMuon'],
	'HLT_Mu7p5_L2Mu2_Jpsi_v2': ['Charmonium'],
	'HLT_PFHT300_v2': ['JetHT'],
	'HLT_Mu7p5_Track3p5_Upsilon_v2': ['MuOnia'],
	'HLT_DoubleMu8_Mass8_PFHT300_v4': ['DoubleMuon'],
	'HLT_Mu23NoFiltersNoVtx_Photon23_CaloIdL_v2': ['MuonEG'],
	'\r\n': [''],
	'HLT_Mu17_Mu8_v1': ['DoubleMuon'],
	'HLT_PFHT200_v2': ['JetHT']
}

triggersGroupMap = {
	'HLT_L1SingleMu16_v1': ['null'],
	'HLT_HT350_DisplacedDijet80_Tight_DisplacedTrack_v2': ['null'],
	'HLT_Ele27_eta2p1_WPLoose_Gsf_LooseIsoPFTau20_v3': ['null'],
	'HLT_Photon22_R9Id90_HE10_Iso40_EBOnly_PFMET40_v3': ['null'],
	'HLT_DoubleMediumIsoPFTau35_Trk1_eta2p1_Reg_v2': ['null'],
	'HLT_DoublePhoton85_v2': ['null'],
	'HLT_Dimuon0er16_Jpsi_NoOS_NoVertexing_v2': ['null'],
	'HLT_PFHT650_WideJetMJJ900DEtaJJ1p5_v3': ['null'],
	'HLT_DoubleMu23NoFiltersNoVtxDisplaced_v2': ['null'],
	'HLT_Photon30_v3': ['null'],
	'HLT_Mu17_TrkIsoVVL_TkMu8_TrkIsoVVL_v2': ['null'],
	'HLT_Mu55_v1': ['null'],
	'MC_CaloMET_JetIdCleaned_v1': ['null'],
	'HLT_PFMETNoMu110_PFMHTNoMu110_IDTight_v1': ['null'],
	'HLT_Rsq0p02_MR300_TriPFJet80_60_40_DoubleBTagCSV_p063_Mbb60_200_v1': ['null'],
	'HLT_HT500_DisplacedDijet40_Inclusive_v2': ['null'],
	'HLT_Mu20_Mu10_v1': ['null'],
	'HLT_DoubleJetsC112_DoubleBTagCSV_p026_DoublePFJetsC172_v1': ['null'],
	'HLT_Ele27_WPLoose_Gsf_CentralPFJet30_BTagCSV_p063_v1': ['null'],
	'HLT_DiPFJet40_DEta3p5_MJJ600_PFMETNoMu80_v1': ['null'],
	'HLT_DiPFJet15_NoCaloMatched_v1': ['null'],
	'HLT_Mu17_v2': ['null'],
	'HLT_Mu33NoFiltersNoVtxDisplaced_DisplacedJet50_Loose_v2': ['null'],
	'HLT_HT425_v1': ['null'],
	'MC_ReducedIterativeTracking_v1': ['null'],
	'HLT_Photon120_R9Id90_HE10_Iso40_EBOnly_VBF_v2': ['null'],
	'HLT_TkMu24_eta2p1_v2': ['null'],
	'DST_HT250_CaloScouting_v2': ['null'],
	'HLT_PFJet400_v4': ['null'],
	'HLT_Ele115_CaloIdVT_GsfTrkIdT_v2': ['null'],
	'HLT_PFJet260_v4': ['null'],
	'HLT_Photon36_R9Id90_HE10_IsoM_v3': ['null'],
	'HLT_AK4PFJet100_v3': ['null'],
	'HLT_Photon50_R9Id90_HE10_Iso40_EBOnly_PFMET40_v3': ['null'],
	'HLT_PFMET300_v1': ['null'],
	'HLT_Ele8_CaloIdL_TrackIdL_IsoVL_PFJet30_v1': ['null'],
	'HLT_Ele27_eta2p1_WPLoose_Gsf_v2': ['null'],
	'HLT_Photon50_R9Id90_HE10_IsoM_v3': ['null'],
	'HLT_Mu28NoFiltersNoVtx_DisplacedJet40_Loose_v2': ['null'],
	'HLT_Mu28NoFiltersNoVtxDisplaced_Photon28_CaloIdL_v2': ['null'],
	'HLT_Mu7p5_Track3p5_Jpsi_v2': ['null'],
	'HLT_PFHT800_v2': ['null'],
	'HLT_DiCentralPFJet55_PFMET110_v1': ['null'],
	'HLT_Ele27_eta2p1_WPTight_Gsf_v2': ['null'],
	'HLT_AK4PFJet30_v3': ['null'],
	'HLT_IsoMu22_v2': ['null'],
	'HLT_Rsq0p30_v2': ['null'],
	'HLT_IsoTkMu27_v3': ['null'],
	'HLT_Mu17_Photon35_CaloIdL_L1ISO_v3': ['null'],
	'HLT_DiPFJetAve80_HFJEC_v3': ['null'],
	'HLT_PixelTracks_Multiplicity135ForEndOfFill_v1': ['null'],
	'HLT_RsqMR240_Rsq0p09_MR200_v2': ['null'],
	'MC_PFMET_v2': ['null'],
	'HLT_Mu40_eta2p1_PFJet200_PFJet50_v3': ['null'],
	'HLT_LooseIsoPFTau50_Trk30_eta2p1_v3': ['null'],
	'HLT_PFMET120_BTagCSV_p067_v1': ['null'],
	'HLT_PFHT650_4JetPt50_v1': ['null'],
	'HLT_Ele10_CaloIdM_TrackIdM_CentralPFJet30_BTagCSV_p13_v1': ['null'],
	'HLT_Photon75_R9Id90_HE10_Iso40_EBOnly_PFMET40_v3': ['null'],
	'HLT_PFHT350_DiPFJetAve90_PFAlphaT0p52_v2': ['null'],
	'HLT_TkMu20_v2': ['null'],
	'HLT_IsoMu20_v3': ['null'],
	'HLT_TrkMu17_DoubleTrkMu8NoFiltersNoVtx_v2': ['null'],
	'HLT_IsoMu18_CentralPFJet30_BTagCSV_p063_v1': ['null'],
	'HLT_DoubleEle8_CaloIdM_TrackIdM_Mass8_PFHT250_v1': ['null'],
	'MC_Diphoton10_10_R9Id_OR_IsoCaloId_AND_HE_R9Id_Mass10_v1': ['null'],
	'HLT_Photon90_CaloIdL_PFHT500_v3': ['null'],
	'HLT_LooseIsoPFTau50_Trk30_eta2p1_MET120_v1': ['null'],
	'HLT_Physics_v2': ['null'],
	'HLT_Mu42NoFiltersNoVtx_Photon42_CaloIdL_v2': ['null'],
	'HLT_AK4CaloJet30_v3': ['null'],
	'HLT_Photon22_R9Id90_HE10_Iso40_EBOnly_VBF_v2': ['null'],
	'HLT_Photon90_CaloIdL_PFHT600_v2': ['null'],
	'HLT_MET60_IsoTrk35_Loose_v1': ['null'],
	'HLT_PFHT200_DiPFJetAve90_PFAlphaT0p63_v2': ['null'],
	'HLT_HT500to550_v1': ['null'],
	'HLT_Rsq0p25_v2': ['null'],
	'HLT_DiPFJetAve60_v2': ['null'],
	'HLT_Mu12_Photon25_CaloIdL_v3': ['null'],
	'HLT_Mu17_Photon22_CaloIdL_L1ISO_v1': ['null'],
	'HLT_DiPFJetAve140_v2': ['null'],
	'HLT_Mu38NoFiltersNoVtxDisplaced_DisplacedJet60_Loose_v2': ['null'],
	'HLT_IsoMu17_eta2p1_LooseIsoPFTau20_SingleL1_v4': ['null'],
	'DST_CaloJet40_CaloScouting_PFScouting_v1': ['null'],
	'HLT_HT450to470_v1': ['null'],
	'HLT_CaloJet500_NoJetID_v2': ['null'],
	'HLT_DoubleJet90_Double30_TripleBTagCSV_p087_v1': ['null'],
	'HLT_Dimuon10_Jpsi_Barrel_v2': ['null'],
	'HLT_DiPFJetAve35_HFJEC_v1': ['null'],
	'HLT_Mu17_TrkIsoVVL_Ele12_CaloIdL_TrackIdL_IsoVL_v3': ['null'],
	'HLT_Mu8_TrkIsoVVL_Ele17_CaloIdL_TrackIdL_IsoVL_v3': ['null'],
	'HLT_IsoMu17_eta2p1_MediumIsoPFTau40_Trk1_eta2p1_Reg_v5': ['null'],
	'HLT_IsoMu17_eta2p1_MediumIsoPFTau35_Trk1_eta2p1_Reg_v3': ['null'],
	'HLT_JetE70_NoBPTX3BX_NoHalo_v2': ['null'],
	'HLT_CaloMHTNoPU90_PFMET90_PFMHT90_IDTight_BTagCSV_p067_v1': ['null'],
	'HLT_VBF_DisplacedJet40_DisplacedTrack_2TrackIP2DSig5_v2': ['null'],
	'HLT_PFHT300_PFMET110_v1': ['null'],
	'HLT_RsqMR270_Rsq0p09_MR200_v2': ['null'],
	'HLT_DiPFJet15_FBEta3_NoCaloMatched_v1': ['null'],
	'HLT_Mu38NoFiltersNoVtx_DisplacedJet60_Loose_v2': ['null'],
	'HLT_DiPFJet25_NoCaloMatched_v1': ['null'],
	'HLT_HT275_v1': ['null'],
	'HLT_Photon75_R9Id90_HE10_IsoM_v3': ['null'],
	'HLT_Photon120_R9Id90_HE10_IsoM_v3': ['null'],
	'HLT_Ele22_eta2p1_WPTight_Gsf_v3': ['null'],
	'HLT_PFJet80_v4': ['null'],
	'HLT_L1MinimumBiasHF_OR_v1': ['null'],
	'HLT_Ele27_eta2p1_WPLoose_Gsf_DoubleMediumIsoPFTau35_Trk1_eta2p1_Reg_v2': ['null'],
	'HLT_PFHT350_DiPFJetAve90_PFAlphaT0p53_v2': ['null'],
	'MC_DoubleEle5_CaloIdL_GsfTrkIdVL_MW_v2': ['null'],
	'HLT_HT2500_v1': ['null'],
	'HLT_TrkMu15_DoubleTrkMu5NoFiltersNoVtx_v2': ['null'],
	'HLT_QuadPFJet_VBF_v4': ['null'],
	'HLT_PFHT400_v2': ['null'],
	'HLT_PFTau140_eta2p1_v1': ['null'],
	'HLT_Ele23_Ele12_CaloIdL_TrackIdL_IsoVL_DZ_v3': ['null'],
	'HLT_DoubleJetsC100_DoubleBTagCSV_p014_DoublePFJetsC100MaxDeta1p6_v1': ['null'],
	'HLT_Ele27_HighEta_Ele20_Mass55_v1': ['null'],
	'HLT_DiPFJetAve100_HFJEC_v3': ['null'],
	'AlCa_DoubleEle_CaloIdL_TrackIdL_IsoVL_DZ_v1': ['null'],
	'HLT_DoubleMu4_JpsiTrk_Displaced_v2': ['null'],
	'HLT_PFMET170_JetIdCleaned_v2': ['null'],
	'HLT_HT350_DisplacedDijet80_DisplacedTrack_v2': ['null'],
	'MC_PFHT_v2': ['null'],
	'HLT_AK8DiPFJet280_200_TrimMass30_v1': ['null'],
	'HLT_DoubleEle8_CaloIdM_TrackIdM_Mass8_PFHT300_v4': ['null'],
	'HLT_PFHT450_SixJet40_v3': ['null'],
	'HLT_DoubleEle24_22_eta2p1_WPLoose_Gsf_v2': ['null'],
	'HLT_Mu17_TrkIsoVVL_TkMu8_TrkIsoVVL_DZ_v2': ['null'],
	'HLT_MonoCentralPFJet80_PFMETNoMu110_PFMHTNoMu110_IDTight_v1': ['null'],
	'HLT_Mu17_TrkIsoVVL_Mu8_TrkIsoVVL_DZ_v2': ['null'],
	'HLT_PFHT350_v3': ['null'],
	'HLT_Mu24_eta2p1_v2': ['null'],
	'HLT_Ele23_CaloIdL_TrackIdL_IsoVL_v3': ['null'],
	'HLT_DoubleJetsC100_DoubleBTagCSV_p026_DoublePFJetsC160_v1': ['null'],
	'AlCa_LumiPixels_Random_v1': ['null'],
	'MC_CaloHT_v1': ['null'],
	'HLT_Ele27_WPLoose_Gsf_v1': ['null'],
	'HLT_RsqMR270_Rsq0p09_MR200_4jet_v2': ['null'],
	'HLT_AK8PFHT600_TrimR0p1PT0p03Mass50_BTagCSV_p20_v1': ['null'],
	'HLT_Mu17_Photon30_CaloIdL_L1ISO_v3': ['null'],
	'HLT_DoubleEle33_CaloIdL_MW_v1': ['null'],
	'DST_HT410_PFScouting_v1': ['null'],
	'HLT_JetE50_NoBPTX3BX_NoHalo_v2': ['null'],
	'HLT_Mu8_Ele8_CaloIdM_TrackIdM_Mass8_PFHT250_v1': ['null'],
	'HLT_QuadMuon0_Dimuon0_Jpsi_v2': ['null'],
	'HLT_Mu17_Mu8_SameSign_DZ_v1': ['null'],
	'HLT_PFMETNoMu120_PFMHTNoMu120_IDTight_v1': ['null'],
	'HLT_Photon135_PFMET100_v1': ['null'],
	'HLT_VBF_DisplacedJet40_TightID_DisplacedTrack_v2': ['null'],
	'HLT_QuadPFJet_BTagCSV_p016_p11_VBF_Mqq240_v1': ['null'],
	'HLT_Photon120_v3': ['null'],
	'HLT_Mu15_IsoVVVL_PFHT600_v3': ['null'],
	'DST_L1HTT_CaloScouting_PFScouting_v1': ['null'],
	'HLT_DoubleMu38NoFiltersNoVtx_v2': ['null'],
	'HLT_Ele23_CaloIdM_TrackIdM_PFJet30_v3': ['null'],
	'HLT_AK8DiPFJet280_200_TrimMass30_BTagCSV_p20_v1': ['null'],
	'HLT_Mu23_TrkIsoVVL_Ele12_CaloIdL_TrackIdL_IsoVL_v3': ['null'],
	'HLT_PFTau120_eta2p1_v1': ['null'],
	'HLT_BTagMu_Jet300_Mu5_v2': ['null'],
	'HLT_QuadPFJet_BTagCSV_p016_p11_VBF_Mqq200_v1': ['null'],
	'HLT_JetE30_NoBPTX_v2': ['null'],
	'AlCa_DoubleEle_CaloIdL_TrackIdL_IsoVL_v1': ['null'],
	'HLT_Mu300_v1': ['null'],
	'HLT_CaloMHTNoPU90_PFMET90_PFMHT90_IDTight_v2': ['null'],
	'HLT_DoubleMu28NoFiltersNoVtxDisplaced_v2': ['null'],
	'HLT_HcalUTCA_v2': ['null'],
	'AlCa_EcalPi0EEonly_v3': ['null'],
	'HLT_DiPFJetAve320_v2': ['null'],
	'HLT_Mu25_TkMu0_dEta18_Onia_v2': ['null'],
	'HLT_IsoMu22_CentralPFJet30_BTagCSV_p063_v1': ['null'],
	'HLT_Ele27_eta2p1_WPLoose_Gsf_HT200_v2': ['null'],
	'HLT_PFJet450_v4': ['null'],
	'HLT_AK8PFHT700_TrimR0p1PT0p03Mass50_v3': ['null'],
	'HLT_PixelTracks_Multiplicity85ForEndOfFill_v1': ['null'],
	'HLT_Mu28NoFiltersNoVtx_CentralCaloJet40_v2': ['null'],
	'HLT_IsoMu16_eta2p1_MET30_LooseIsoPFTau50_Trk30_eta2p1_v1': ['null'],
	'HLT_L2Mu10_NoVertex_NoBPTX_v2': ['null'],
	'MC_CaloMET_v1': ['null'],
	'MC_DoubleMu_TrkIsoVVL_DZ_v1': ['null'],
	'HLT_IsoMu18_TriCentralPFJet50_40_30_v2': ['null'],
	'HLT_PixelTracks_Multiplicity110ForEndOfFill_v1': ['null'],
	'HLT_PFJet320_v4': ['null'],
	'HLT_Mu38NoFiltersNoVtxDisplaced_DisplacedJet60_Tight_v2': ['null'],
	'HLT_DoubleMu4_LowMassNonResonantTrk_Displaced_v2': ['null'],
	'HLT_Mu16_TkMu0_dEta18_Onia_v2': ['null'],
	'HLT_Ele22_eta2p1_WPLoose_Gsf_LooseIsoPFTau20_SingleL1_v2': ['null'],
	'HLT_DiPFJetAve200_v2': ['null'],
	'HLT_PFHT300_PFMET100_v1': ['null'],
	'HLT_IsoMu16_eta2p1_MET30_v1': ['null'],
	'HLT_IsoMu27_v3': ['null'],
	'HLT_BTagMu_DiJet40_Mu5_v2': ['null'],
	'HLT_PFHT250_v2': ['null'],
	'HLT_Dimuon8_PsiPrime_Barrel_v2': ['null'],
	'HLT_Mu7p5_Track7_Jpsi_v2': ['null'],
	'HLT_DiPFJet25_FBEta3_NoCaloMatched_v1': ['null'],
	'HLT_Photon500_v1': ['null'],
	'HLT_PFMETNoMu90_PFMHTNoMu90_IDTight_v1': ['null'],
	'HLT_Diphoton30PV_18PV_R9Id_AND_IsoCaloId_AND_HE_R9Id_DoublePixelVeto_Mass55_v1': ['null'],
	'HLT_PFHT600_v3': ['null'],
	'HLT_PFHT550_4JetPt50_v1': ['null'],
	'HLT_Ele45_CaloIdVT_GsfTrkIdT_PFJet200_PFJet50_v3': ['null'],
	'HLT_Ele23_WPLoose_Gsf_CentralPFJet30_BTagCSV_p063_v1': ['null'],
	'HLT_Mu16_TkMu0_dEta18_Phi_v2': ['null'],
	'HLT_VBF_DisplacedJet40_Hadronic_2PromptTrack_v2': ['null'],
	'AlCa_RPCMuonNoTriggers_v2': ['null'],
	'HLT_Mu17_TkMu8_DZ_v2': ['null'],
	'HLT_AK4PFJet50_v3': ['null'],
	'HLT_DiPFJetAve80_v2': ['null'],
	'MC_IsoTkMu15_v3': ['null'],
	'HLT_Ele23_Ele12_CaloIdL_TrackIdL_IsoVL_v3': ['null'],
	'HLT_Photon50_v3': ['null'],
	'HLT_Ele17_Ele12_CaloIdL_TrackIdL_IsoVL_DZ_v3': ['null'],
	'HLT_Ele30WP60_Ele8_Mass55_v2': ['null'],
	'HLT_Photon175_v3': ['null'],
	'HLT_PFMET90_PFMHT90_IDTight_v2': ['null'],
	'HLT_Mu30_Ele30_CaloIdL_GsfTrkIdVL_v3': ['null'],
	'HLT_Ele12_CaloIdL_TrackIdL_IsoVL_v3': ['null'],
	'HLT_PFJet15_NoCaloMatched_v3': ['null'],
	'MC_Ele15_Ele10_CaloIdL_TrackIdL_IsoVL_DZ_v2': ['null'],
	'HLT_Dimuon13_PsiPrime_v2': ['null'],
	'AlCa_LumiPixels_ZeroBias_v2': ['null'],
	'HLT_Mu14er_PFMET100_v1': ['null'],
	'HLT_DoubleEle33_CaloIdL_GsfTrkIdVL_v3': ['null'],
	'HLT_HISinglePhoton60_v2': ['null'],
	'HLT_Mu10_TrkIsoVVL_DiPFJet40_DEta3p5_MJJ750_HTT350_PFMETNoMu60_v1': ['null'],
	'HLT_Mu16_eta2p1_MET30_v1': ['null'],
	'AlCa_EcalPhiSym_v3': ['null'],
	'HLT_VBF_DisplacedJet40_VTightID_Hadronic_v2': ['null'],
	'HLT_IsoMu17_eta2p1_v3': ['null'],
	'HLT_Rsq0p02_MR300_TriPFJet80_60_40_BTagCSV_p063_p20_Mbb60_200_v1': ['null'],
	'HLT_PFHT200_PFAlphaT0p51_v2': ['null'],
	'HLT_Ele30WP60_SC4_Mass55_v3': ['null'],
	'HLT_Mu6_PFHT200_PFMET100_v1': ['null'],
	'HLT_Mu15_IsoVVVL_PFHT350_PFMET50_v2': ['null'],
	'HLT_Photon120_R9Id90_HE10_Iso40_EBOnly_PFMET40_v3': ['null'],
	'HLT_Ele15_IsoVVVL_PFHT350_v2': ['null'],
	'HLT_DiPFJetAve260_v2': ['null'],
	'HLT_PFJet60_v4': ['null'],
	'MC_Ele5_WPLoose_Gsf_v2': ['null'],
	'HLT_Photon165_R9Id90_HE10_IsoM_v3': ['null'],
	'HLT_L1_TripleJet_VBF_v4': ['null'],
	'HLT_PFJet500_v4': ['null'],
	'HLT_Photon75_R9Id90_HE10_Iso40_EBOnly_VBF_v2': ['null'],
	'HLT_Photon90_R9Id90_HE10_Iso40_EBOnly_PFMET40_v3': ['null'],
	'HLT_Dimuon6_Jpsi_NoVertexing_v2': ['null'],
	'HLT_Photon90_R9Id90_HE10_IsoM_v3': ['null'],
	'HLT_PFHT250_DiPFJetAve90_PFAlphaT0p55_v2': ['null'],
	'HLT_Ele105_CaloIdVT_GsfTrkIdT_v3': ['null'],
	'DST_HT450_PFScouting_v1': ['null'],
	'HLT_HT550to650_v1': ['null'],
	'HLT_QuadPFJet_BTagCSV_p016_VBF_Mqq460_v1': ['null'],
	'HLT_Diphoton30_18_Solid_R9Id_AND_IsoCaloId_AND_HE_R9Id_Mass55_v1': ['null'],
	'HLT_HT430to450_v1': ['null'],
	'MC_AK8PFHT_v2': ['null'],
	'HLT_QuadJet45_TripleBTagCSV_p087_v1': ['null'],
	'HLT_HT350_DisplacedDijet40_Inclusive_v1': ['null'],
	'MC_AK8PFJets_v2': ['null'],
	'HLT_DoubleMu4_3_Jpsi_Displaced_v2': ['null'],
	'HLT_DoubleMediumIsoPFTau40_Trk1_eta2p1_Reg_v4': ['null'],
	'HLT_Ele8_CaloIdM_TrackIdM_PFJet30_v3': ['null'],
	'HLT_IsoTkMu20_v4': ['null'],
	'HLT_Mu33NoFiltersNoVtxDisplaced_DisplacedJet50_Tight_v2': ['null'],
	'HLT_DoublePhoton60_v1': ['null'],
	'HLT_AK4PFJet80_v3': ['null'],
	'HLT_Dimuon0_Upsilon_Muon_v2': ['null'],
	'HLT_HT470to500_v1': ['null'],
	'HLT_Mu23_TrkIsoVVL_Ele8_CaloIdL_TrackIdL_IsoVL_v1': ['null'],
	'HLT_DoubleJetsC100_SingleBTagCSV_p014_v1': ['null'],
	'AlCa_EcalEtaEEonly_v3': ['null'],
	'HLT_Ele15_IsoVVVL_BTagCSV_p067_PFHT400_v1': ['null'],
	'HLT_Ele23_WPLoose_Gsf_TriCentralPFJet50_40_30_v2': ['null'],
	'HLT_Mu12_Photon25_CaloIdL_L1ISO_v3': ['null'],
	'HLT_Ele35_CaloIdVT_GsfTrkIdT_PFJet150_PFJet50_v1': ['null'],
	'HLT_HT350_DisplacedDijet40_DisplacedTrack_v2': ['null'],
	'HLT_DoubleJetsC100_SingleBTagCSV_p014_SinglePFJetC350_v1': ['null'],
	'HLT_AK4CaloJet100_v2': ['null'],
	'HLT_HISinglePhoton10_v2': ['null'],
	'HLT_Ele23_CaloIdL_TrackIdL_IsoVL_PFJet30_v3': ['null'],
	'HLT_BTagMu_DiJet20_Mu5_v2': ['null'],
	'HLT_AK8PFJet360_TrimMass30_v3': ['null'],
	'HLT_HT650_v2': ['null'],
	'HLT_HT750_DisplacedDijet80_Inclusive_v2': ['null'],
	'HLT_MET200_v1': ['null'],
	'HLT_L2Mu10_NoVertex_NoBPTX3BX_NoHalo_v2': ['null'],
	'HLT_DiPFJetAve300_HFJEC_v3': ['null'],
	'HLT_MonoCentralPFJet80_PFMETNoMu90_PFMHTNoMu90_IDTight_v1': ['null'],
	'HLT_Ele15_IsoVVVL_PFHT600_v3': ['null'],
	'HLT_PFMET400_v1': ['null'],
	'HLT_Mu7p5_Track2_Jpsi_v2': ['null'],
	'HLT_Dimuon0er16_Jpsi_NoVertexing_v2': ['null'],
	'HLT_ZeroBias_IsolatedBunches_v1': ['null'],
	'HLT_HT400_DisplacedDijet40_Inclusive_v2': ['null'],
	'HLT_Mu8_v3': ['null'],
	'HLT_IsoTrackHB_v1': ['null'],
	'HLT_PFMET170_HBHECleaned_v2': ['null'],
	'MC_PFMHT_v2': ['null'],
	'HLT_JetE30_NoBPTX3BX_NoHalo_v2': ['null'],
	'HLT_PFMET100_PFMHT100_IDTight_v2': ['null'],
	'DST_ZeroBias_PFScouting_v1': ['null'],
	'HLT_Mu6_PFHT200_PFMET80_BTagCSV_p067_v1': ['null'],
	'HLT_Ele27_WPLoose_Gsf_WHbbBoost_v2': ['null'],
	'HLT_Mu40_TkMu11_v2': ['null'],
	'HLT_DiPFJet40_DEta3p5_MJJ600_PFMETNoMu140_v1': ['null'],
	'HLT_BTagMu_DiJet70_Mu5_v2': ['null'],
	'HLT_Mu20_v2': ['null'],
	'HLT_Mu8_TrkIsoVVL_Ele23_CaloIdL_TrackIdL_IsoVL_v3': ['null'],
	'HLT_Photon75_v3': ['null'],
	'MC_AK4PFJets_v2': ['null'],
	'HLT_PFMETNoMu100_PFMHTNoMu100_IDTight_v1': ['null'],
	'HLT_HT200_DisplacedDijet40_DisplacedTrack_v1': ['null'],
	'HLT_L2Mu40_NoVertex_3Sta_NoBPTX3BX_NoHalo_v2': ['null'],
	'HLT_Diphoton30_18_R9Id_OR_IsoCaloId_AND_HE_R9Id_Mass90_v1': ['null'],
	'HLT_Mu7p5_Track7_Upsilon_v2': ['null'],
	'HLT_PFHT250_DiPFJetAve90_PFAlphaT0p58_v2': ['null'],
	'HLT_L1SingleMuOpen_v2': ['null'],
	'HLT_Ele27_WPLoose_Gsf_TriCentralPFJet50_40_30_v1': ['null'],
	'HLT_IsoTkMu22_v2': ['null'],
	'HLT_DiSC30_18_EIso_AND_HE_Mass70_v1': ['null'],
	'HLT_Mu8_Ele8_CaloIdM_TrackIdM_Mass8_PFHT300_v4': ['null'],
	'HLT_DiMu9_Ele9_CaloIdL_TrackIdL_v3': ['null'],
	'HLT_DiPFJetAve160_HFJEC_v3': ['null'],
	'HLT_PFJet25_NoCaloMatched_v1': ['null'],
	'HLT_IsoMu20_eta2p1_LooseIsoPFTau20_v3': ['null'],
	'HLT_Ele23_WPLoose_Gsf_v3': ['null'],
	'HLT_Mu17_TrkIsoVVL_Mu8_TrkIsoVVL_v2': ['null'],
	'HLT_Random_v1': ['null'],
	'HLT_HT200_v1': ['null'],
	'HLT_PFJet140_v4': ['null'],
	'HLT_PFHT400_SixJet30_DoubleBTagCSV_p056_v1': ['null'],
	'HLT_LooseIsoPFTau50_Trk30_eta2p1_MET80_v1': ['null'],
	'HLT_Dimuon8_Upsilon_Barrel_v2': ['null'],
	'HLT_Mu27_TkMu8_v2': ['null'],
	'HLT_L1Tech_DT_GlobalOR_v2': ['null'],
	'HLT_DiPFJetAve220_HFJEC_v3': ['null'],
	'HLT_DoubleMu4_3_Bs_v2': ['null'],
	'HLT_PFMET120_Mu5_v1': ['null'],
	'HLT_MonoCentralPFJet80_PFMETNoMu100_PFMHTNoMu100_IDTight_v1': ['null'],
	'HLT_DiPFJetAve60_HFJEC_v3': ['null'],
	'HLT_QuadMuon0_Dimuon0_Upsilon_v2': ['null'],
	'HLT_L2Mu10_v1': ['null'],
	'HLT_Mu50_v2': ['null'],
	'HLT_Photon50_R9Id90_HE10_Iso40_EBOnly_VBF_v2': ['null'],
	'HLT_VBF_DisplacedJet40_DisplacedTrack_v2': ['null'],
	'HLT_Mu3er_PFHT140_PFMET125_v1': ['null'],
	'AlCa_EcalPi0EBonly_v3': ['null'],
	'HLT_MET90_IsoTrk50_v2': ['null'],
	'HLT_HISinglePhoton20_v2': ['null'],
	'HLT_ECALHT800_v2': ['null'],
	'HLT_PFMET110_PFMHT110_IDTight_v2': ['null'],
	'HLT_BTagMu_DiJet110_Mu5_v2': ['null'],
	'DST_DoubleMu3_Mass10_PFScouting_v1': ['null'],
	'HLT_PFHT900_v1': ['null'],
	'HLT_DoubleMu33NoFiltersNoVtx_v2': ['null'],
	'HLT_PFTau95_eta2p1_v1': ['null'],
	'HLT_Mu45_eta2p1_v2': ['null'],
	'HLT_Ele23_WPLoose_Gsf_WHbbBoost_v2': ['null'],
	'HLT_Ele17_CaloIdL_TrackIdL_IsoVL_PFJet30_v1': ['null'],
	'HLT_Ele12_CaloIdL_TrackIdL_IsoVL_PFJet30_v3': ['null'],
	'HLT_DoubleJetsC100_SingleBTagCSV_p026_SinglePFJetC350_v1': ['null'],
	'HLT_Ele17_CaloIdM_TrackIdM_PFJet30_v1': ['null'],
	'HLT_MonoCentralPFJet80_PFMETNoMu120_PFMHTNoMu120_IDTight_v1': ['null'],
	'HLT_Ele22_eta2p1_WPLoose_Gsf_v3': ['null'],
	'HLT_VBF_DisplacedJet40_Hadronic_v2': ['null'],
	'HLT_Mu30_eta2p1_PFJet150_PFJet50_v1': ['null'],
	'HLT_L2Mu35_NoVertex_3Sta_NoBPTX3BX_NoHalo_v2': ['null'],
	'HLT_PFHT650_v3': ['null'],
	'HLT_DoubleMu8_Mass8_PFHT250_v1': ['null'],
	'HLT_HT250_DisplacedDijet40_DisplacedTrack_v2': ['null'],
	'HLT_Photon36_R9Id90_HE10_Iso40_EBOnly_VBF_v2': ['null'],
	'HLT_Mu17_Mu8_DZ_v2': ['null'],
	'MC_DoubleMuNoFiltersNoVtx_v1': ['null'],
	'HLT_L2DoubleMu38_NoVertex_2Cha_Angle2p5_Mass10_v2': ['null'],
	'HLT_TkMu27_v2': ['null'],
	'HLT_Mu33NoFiltersNoVtxDisplaced_Photon33_CaloIdL_v2': ['null'],
	'HLT_PFHT300_DiPFJetAve90_PFAlphaT0p53_v2': ['null'],
	'HLT_Photon90_v3': ['null'],
	'HLT_PFMET120_PFMHT120_IDTight_v2': ['null'],
	'HLT_Photon36_R9Id90_HE10_Iso40_EBOnly_PFMET40_v3': ['null'],
	'HLT_QuadJet45_DoubleBTagCSV_p087_v1': ['null'],
	'HLT_HcalPhiSym_v2': ['null'],
	'HLT_PFMET170_NoiseCleaned_v3': ['null'],
	'HLT_MET75_IsoTrk50_v2': ['null'],
	'HLT_Ele12_CaloIdM_TrackIdM_PFJet30_v3': ['null'],
	'DST_L1DoubleMu_PFScouting_v1': ['null'],
	'HLT_MET250_v1': ['null'],
	'MC_DoubleGlbTrkMu_TrkIsoVVL_DZ_v1': ['null'],
	'HLT_Mu38NoFiltersNoVtx_Photon38_CaloIdL_v2': ['null'],
	'HLT_VBF_DisplacedJet40_TightID_Hadronic_v2': ['null'],
	'HLT_Mu7p5_L2Mu2_Upsilon_v2': ['null'],
	'HLT_Ele17_CaloIdL_TrackIdL_IsoVL_v2': ['null'],
	'HLT_PFHT650_WideJetMJJ950DEtaJJ1p5_v3': ['null'],
	'HLT_L1SingleMuOpen_DT_v2': ['null'],
	'HLT_DiPFJetAve25_HFJEC_v1': ['null'],
	'HLT_Mu20_Mu10_DZ_v1': ['null'],
	'HLT_DiPFJetAve500_v2': ['null'],
	'HLT_PFMET170_NotCleaned_v1': ['null'],
	'HLT_Mu20_Mu10_SameSign_DZ_v1': ['null'],
	'HLT_Photon42_R9Id85_OR_CaloId24b40e_Iso50T80L_Photon25_AND_HE10_R9Id65_Eta2_Mass15_v2': ['null'],
	'HLT_Mu15_IsoVVVL_BTagCSV_p067_PFHT400_v1': ['null'],
	'MC_AK4CaloJets_v1': ['null'],
	'HLT_Dimuon0_Phi_Barrel_v2': ['null'],
	'HLT_PFHT450_SixJet40_BTagCSV_p056_v1': ['null'],
	'HLT_PFHT475_v2': ['null'],
	'HLT_Mu7p5_Track2_Upsilon_v2': ['null'],
	'HLT_Mu12_Photon25_CaloIdL_L1OR_v3': ['null'],
	'HLT_Dimuon20_Jpsi_v2': ['null'],
	'HLT_PFHT400_DiPFJetAve90_PFAlphaT0p52_v2': ['null'],
	'HLT_Photon165_HE10_v3': ['null'],
	'HLT_Dimuon0_Jpsi_Muon_v2': ['null'],
	'HLT_Dimuon13_Upsilon_v2': ['null'],
	'HLT_IsoMu22_TriCentralPFJet50_40_30_v2': ['null'],
	'HLT_AK4CaloJet40_v2': ['null'],
	'HLT_Diphoton30_18_R9Id_OR_IsoCaloId_AND_HE_R9Id_DoublePixelSeedMatch_Mass70_v1': ['null'],
	'MC_IsoMu_v4': ['null'],
	'HLT_DoubleJet90_Double30_DoubleBTagCSV_p087_v1': ['null'],
	'HLT_PFJet40_v4': ['null'],
	'HLT_DoubleEle33_CaloIdL_v1': ['null'],
	'HLT_AK8DiPFJet250_200_TrimMass30_BTagCSV_p20_v1': ['null'],
	'HLT_DiPFJetAve40_v2': ['null'],
	'HLT_PFHT200_DiPFJetAve90_PFAlphaT0p57_v2': ['null'],
	'HLT_QuadPFJet_BTagCSV_p016_VBF_Mqq500_v1': ['null'],
	'HLT_DoubleIsoMu17_eta2p1_v3': ['null'],
	'HLT_DoubleJetsC100_SingleBTagCSV_p026_v1': ['null'],
	'HLT_AK4CaloJet80_v2': ['null'],
	'HLT_L2DoubleMu23_NoVertex_v2': ['null'],
	'HLT_DoubleJetsC112_DoubleBTagCSV_p014_DoublePFJetsC112MaxDeta1p6_v1': ['null'],
	'HLT_HT550_DisplacedDijet40_Inclusive_v2': ['null'],
	'DST_L1HTT_BTagScouting_v1': ['null'],
	'HLT_Photon36_v3': ['null'],
	'AlCa_RPCMuonNormalisation_v2': ['null'],
	'HLT_HISinglePhoton40_v2': ['null'],
	'HLT_PFHT400_DiPFJetAve90_PFAlphaT0p51_v2': ['null'],
	'DST_HT450_BTagScouting_v1': ['null'],
	'HLT_Mu8_DiEle12_CaloIdL_TrackIdL_v3': ['null'],
	'DST_CaloJet40_BTagScouting_v1': ['null'],
	'HLT_AK8PFHT650_TrimR0p1PT0p03Mass50_v2': ['null'],
	'HLT_Photon30_R9Id90_HE10_IsoM_v3': ['null'],
	'HLT_GlobalRunHPDNoise_v3': ['null'],
	'HLT_TripleMu_12_10_5_v2': ['null'],
	'MC_AK8TrimPFJets_v2': ['null'],
	'HLT_PFJet200_v4': ['null'],
	'HLT_PFHT125_v1': ['null'],
	'HLT_MET300_v1': ['null'],
	'HLT_Mu8_TrkIsoVVL_v3': ['null'],
	'HLT_Photon36_R9Id85_OR_CaloId24b40e_Iso50T80L_Photon22_AND_HE10_R9Id65_Eta2_Mass15_v2': ['null'],
	'DST_L1DoubleMu_BTagScouting_v1': ['null'],
	'HLT_AK4CaloJet50_v2': ['null'],
	'HLT_PixelTracks_Multiplicity60ForEndOfFill_v1': ['null'],
	'HLT_ZeroBias_v2': ['null'],
	'HLT_PFHT750_4JetPt50_v3': ['null'],
	'HLT_Mu10_CentralPFJet30_BTagCSV_p13_v1': ['null'],
	'HLT_Ele16_Ele12_Ele8_CaloIdL_TrackIdL_v3': ['null'],
	'HLT_HISinglePhoton15_v2': ['null'],
	'HLT_HT2000_v1': ['null'],
	'DST_ZeroBias_BTagScouting_v1': ['null'],
	'HLT_Ele22_eta2p1_WPLoose_Gsf_LooseIsoPFTau20_v3': ['null'],
	'HLT_IsoTrackHE_v1': ['null'],
	'MC_CaloMHT_v1': ['null'],
	'HLT_Ele32_eta2p1_WPTight_Gsf_v2': ['null'],
	'HLT_HcalNZS_v2': ['null'],
	'HLT_DoubleMu4_PsiPrimeTrk_Displaced_v2': ['null'],
	'HLT_Ele15_IsoVVVL_PFHT350_PFMET50_v2': ['null'],
	'HLT_Ele17_Ele12_CaloIdL_TrackIdL_IsoVL_v3': ['null'],
	'HLT_PFHT400_SixJet30_v3': ['null'],
	'HLT_Mu350_v1': ['null'],
	'AlCa_EcalEtaEBonly_v3': ['null'],
	'HLT_DoubleEle33_CaloIdL_GsfTrkIdVL_MW_v3': ['null'],
	'HLT_Photon300_NoHE_v2': ['null'],
	'DST_DoubleMu3_Mass10_BTagScouting_v1': ['null'],
	'HLT_Photon22_R9Id90_HE10_IsoM_v2': ['null'],
	'HLT_Mu27_v2': ['null'],
	'HLT_IsoTkMu18_v2': ['null'],
	'AlCa_SingleEle_WPVeryLoose_Gsf_v1': ['null'],
	'HLT_HT650_DisplacedDijet80_Inclusive_v2': ['null'],
	'HLT_Photon22_v2': ['null'],
	'HLT_Ele27_eta2p1_WPLoose_Gsf_DoubleMediumIsoPFTau40_Trk1_eta2p1_Reg_v3': ['null'],
	'HLT_L2DoubleMu28_NoVertex_2Cha_Angle2p5_Mass10_v2': ['null'],
	'DST_HT410_BTagScouting_v1': ['null'],
	'HLT_L1MinimumBiasHF_AND_v1': ['null'],
	'HLT_HT575_v1': ['null'],
	'HLT_Mu30_TkMu11_v2': ['null'],
	'HLT_PFHT300_DiPFJetAve90_PFAlphaT0p54_v2': ['null'],
	'HLT_DiPFJetAve400_v2': ['null'],
	'HLT_DiPFJetAve15_HFJEC_v1': ['null'],
	'MC_AK8CaloHT_v1': ['null'],
	'HLT_AK8DiPFJet250_200_TrimMass30_v1': ['null'],
	'HLT_Diphoton30EB_18EB_R9Id_OR_IsoCaloId_AND_HE_R9Id_DoublePixelVeto_Mass55_v1': ['null'],
	'HLT_RsqMR240_Rsq0p09_MR200_4jet_v2': ['null'],
	'AlCa_RPCMuonNoHits_v2': ['null'],
	'HLT_Photon90_R9Id90_HE10_Iso40_EBOnly_VBF_v2': ['null'],
	'HLT_PixelTracks_Multiplicity160ForEndOfFill_v1': ['null'],
	'HLT_HT325_v1': ['null'],
	'HLT_Photon600_v1': ['null'],
	'HLT_Mu15_IsoVVVL_PFHT350_v2': ['null'],
	'HLT_VBF_DisplacedJet40_VTightID_DisplacedTrack_v2': ['null'],
	'HLT_VBF_DisplacedJet40_VVTightID_Hadronic_v2': ['null'],
	'HLT_Mu17_TrkIsoVVL_v2': ['null'],
	'HLT_Photon26_R9Id85_OR_CaloId24b40e_Iso50T80L_Photon16_AND_HE10_R9Id65_Eta2_Mass60_v2': ['null'],
	'HLT_Dimuon16_Jpsi_v2': ['null'],
	'HLT_IsoMu17_eta2p1_LooseIsoPFTau20_v4': ['null'],
	'HLT_DoubleMu18NoFiltersNoVtx_v2': ['null'],
	'HLT_VBF_DisplacedJet40_VVTightID_DisplacedTrack_v2': ['null'],
	'HLT_HT410to430_v1': ['null'],
	'HLT_Photon250_NoHE_v2': ['null'],
	'HLT_IsoMu18_v2': ['null'],
	'HLT_Mu7p5_L2Mu2_Jpsi_v2': ['null'],
	'HLT_PFHT300_v2': ['null'],
	'HLT_Mu7p5_Track3p5_Upsilon_v2': ['null'],
	'HLT_DoubleMu8_Mass8_PFHT300_v4': ['null'],
	'HLT_Mu23NoFiltersNoVtx_Photon23_CaloIdL_v2': ['null'],
	'\r\n': ['null'],
	'HLT_Mu17_Mu8_v1': ['null'],
	'HLT_PFHT200_v2': ['null']
}

datasetStreamMap = {
	'HcalHPDNoise': ['PhysicsEGammaCommissioning'],
	'ScoutingCaloCommissioning': ['ScoutingCalo'],
	'JetHT': ['PhysicsHadronsTaus'],
	'ParkingHT500to550': ['Parking'],
	'ParkingHT470to500': ['Parking'],
	'HTMHT': ['PhysicsHadronsTaus'],
	'NoBPTX': ['PhysicsEGammaCommissioning'],
	'SingleElectron': ['PhysicsEGammaCommissioning'],
	'DoubleMuon': ['PhysicsMuons'],
	'MuOnia': ['PhysicsMuons'],
	'ParkingScoutingMonitor': ['PhysicsParkingScoutingMonitor'],
	'AlCaElectron': ['ALCAELECTRON'],
	'ScoutingPFCommissioning': ['ScoutingPF'],
	'RPCMonitor': ['RPCMON'],
	'FSQJets': ['PhysicsEGammaCommissioning'],
	'BTagCSV': ['PhysicsHadronsTaus'],
	'HcalNZS': ['PhysicsEGammaCommissioning'],
	'BTagMu': ['PhysicsHadronsTaus'],
	'MonteCarlo': ['PhysicsEGammaCommissioning'],
	'HINCaloJets': ['PhysicsEndOfFill'],
	'MuonEG': ['PhysicsMuons'],
	'ParkingHT650': ['Parking'],
	'HighMultiplicity85EOF': ['PhysicsEndOfFill'],
	'HLTPhysics': ['PhysicsEGammaCommissioning'],
	'HighMultiplicityEOF': ['PhysicsEndOfFill'],
	'ParkingHT550to650': ['Parking'],
	'ScoutingCaloHT': ['ScoutingCalo'],
	'DoubleMuonLowMass': ['PhysicsMuons'],
	'SinglePhoton': ['PhysicsEGammaCommissioning'],
	'SingleMuon': ['PhysicsMuons'],
	'DisplacedJet': ['PhysicsHadronsTaus'],
	'ZeroBias': ['PhysicsEGammaCommissioning'],
	'HINPhoton': ['PhysicsEndOfFill'],
	'HINPFJets': ['PhysicsEndOfFill'],
	'ParkingHT450to470': ['Parking'],
	'L1MinimumBias': ['PhysicsEGammaCommissioning'],
	'AlCaPhiSym': ['ALCAPHISYM'],
	'Tau': ['PhysicsHadronsTaus'],
	'AlCaP0': ['ALCAP0'],
	'Charmonium': ['PhysicsMuons'],
	'ParkingHT430to450': ['Parking'],
	'AlCaLumiPixels': ['ALCALUMIPIXELS'],
	'MET': ['PhysicsHadronsTaus'],
	'ParkingHT410to430': ['Parking'],
	'DoubleEG': ['PhysicsEGammaCommissioning'],
	'Commissioning': ['PhysicsEGammaCommissioning'],
	'ScoutingPFMuons': ['ScoutingPF'],
	'ScoutingPFHT': ['ScoutingPF']
}

triggersToRemove = [
    ## not in stream A
    'HLT_EcalCalibration_v',
    
    # use UTCA (not simulated in MC)
    'HLT_HcalUTCA_v',
    
    # use NZS (not simulated in MC)
    'HLT_HcalPhiSym_v',
    'HLT_HcalNZS_v',
    
    # fake triggers
    'HLT_BCToEFilter_v',
    'HLT_RemovePileUpDominatedEventsGen_v',
    'HLT_RemovePileUpDominatedEvents_v',
    'HLT_EmFilter_v',
    'HLT_EmGlobalFilter_v',
    'HLT_MuFilter_v',
    'HLT_MuFilterTP_v',

    # trigger without L1 seeds
    'HLT_Random_v',
    'HLT_Physics_v',
]

#triggersGroupMap = dict(triggersGroupMap.items() + triggersL1GroupMap.items())

triggerList = []
L1List = []
HLTList = []
#twoHLTsList = []
primaryDatasetList = []
groupList = []
twoDatasetsList = []
getTriggerString = {}

## Fill triggerList and groupList and datasetList
for trigger in triggersDatasetMap.keys():
    #if trigger[:-1] in triggersToRemove: continue
    if not (trigger in triggerList) : triggerList.append(trigger) 
    for group in triggersGroupMap[trigger]:
        if not group in groupList: groupList.append(group)
    for dataset in triggersDatasetMap[trigger]:
        if not dataset in primaryDatasetList: primaryDatasetList.append(dataset)

## Fill HLTList and L1List
for trigger in triggerList:
    if "HLT_" in trigger: HLTList.append(trigger)
#    elif "L1_" in trigger: L1List.append(trigger)

## Fill getTriggerString get a map from trigger and group names to strings
for trigger in triggerList:
    getTriggerString[trigger]=trigger
    for dataset in triggersDatasetMap[trigger]:
        if dataset in getTriggerString.keys(): getTriggerString[dataset]+='||'+trigger
        else: getTriggerString[dataset]=trigger
    for group in triggersGroupMap[trigger]:
        if group in getTriggerString.keys(): getTriggerString[group]+='||'+trigger
        else: getTriggerString[group]=trigger

## Fill twoGroupsList and getTriggerString
#for group1 in groupList:
#    for group2 in groupList:
#        if (not group1.isdigit()) and (not group2.isdigit()): twoGroups = group1 + "-" + group2
#        if not (twoGroups in twoGroupsList) and ("L1" not in twoGroups):
#            twoGroupsList.append(twoGroups)
#            twoGroupsTrigger="("+(getTriggerString[group1])+")&&("+(getTriggerString[group2])+")"
#            getTriggerString[twoGroups]=twoGroupsTrigger

### Fill twoHLTsList and getTriggerString
#for trigger1 in HLTList:
#    for trigger2 in HLTList:
#        twoHLTs = trigger1 + "-" + trigger2
#        if not (twoHLTs in twoHLTsList):
#            twoHLTsList.append(twoHLTs)
#            twoHLTsTrigger="("+(getTriggerString[trigger1])+")&&("+(getTriggerString[trigger2])+")"
#            getTriggerString[twoHLTs]=twoHLTsTrigger

## Fill string for All group
primaryDataset.append('All_HLT')
groupList.append('All_HLT')
i = 0
for trigger in HLTList:
    if 'All_HLT' in getTriggerString.keys(): getTriggerString['All_HLT']+='||HLT_'+str(i)
    else: getTriggerString['All_HLT']='HLT_0'
    i += 1

## Creates the global OR string fot all L1 paths 
#i = 0
#for trigger in L1List:
#    if 'L1' in getTriggerString.keys(): getTriggerString['L1']+='||L1_'+str(i)
#    else: getTriggerString['L1']='L1_0'
#    i += 1



